name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: 04shubham7
          template: classic 
          base: "header, isocalender, activity, community, repositories, metadata"
          commits_authoring: 04shubham7
          base_hireable: "yes"
          base_indepth: "yes"
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          plugin_achievements: "no"
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_activity: "no"
          plugin_followup: "yes"
          plugin_followup_archived: "yes"
          plugin_followup_indepth: "yes"
          plugin_followup_sections: repositories
          plugin_habits: "no"
          plugin_introduction: "yes"
          plugin_introduction_title: "yes"
          plugin_isocalendar: "yes"
          plugin_isocalendar_duration: half-year
          plugin_languages: "yes"
          plugin_languages_aliases: javascript:JS,typescript:TS
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup,programming
          plugin_languages_colors: github
          plugin_languages_ignored: html,css
          plugin_languages_limit: 12
          plugin_languages_recent_categories: markup,programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: "yes"
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: "yes"
          plugin_notable_from: organization
          plugin_notable_indepth: "yes"
          plugin_notable_repositories: "yes"
          plugin_notable_self: "yes"
          plugin_notable_types: commit
          plugin_repositories: "yes"
          plugin_repositories_order: featured,pinned,starred,random
          plugin_repositories_pinned: 8
          plugin_repositories_random: 3
          plugin_repositories_starred: 3
          plugin_topics: "yes"
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_traffic: "yes"
          plugin_stars: "yes"
          plugin_stars_limit: 4
          plugin_code: "yes"
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_discussions: "yes"
          plugin_discussions_categories: yes
          plugin_gists: "yes"
          plugin_projects: "no"
